### ISSUE TITLE
Deal with serialized data

### ISSUE THREAD

**Issue by simonrjones** [studio24/fix-staging-urls#2]
If field contains seralized data or base64 encoded data script needs to be updated to deal safely with this. At present a replace on serialized data will break

**Comment by johnhunt** [comment]
This is quite hard to do. A starting point would be to at least detect if it's in a serialised string. Fun challenge though I suppose!

**Comment by simonrjones** [comment]
hi - thanks for the feedback John! 

The seralized string is the more important use case since it can pick up on HTML in a serialized string. The unserialize() function can be used to pretty easily detect whether a string is in a valid serialized format. If a string is replaced in a serialized string it will break unpacking it due to the format.

base64 may be less important, though would help with those ridiculous eeCMS base64 encoded database fields.

**Comment by simonrjones** [comment]
Dropping requirement to update base64 encoded data, would be useful for serialized data due to usage in CMSs such as WordPress

**Comment by simonrjones** [comment]
functionality added for arrays stored as serialized data only
